language: cpp

matrix:
    include:
        - os: linux
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-7 libarmadillo-dev libfftw3-dev
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

script:
        - | 
             mkdir build
             cd build
             cmake .. && cmake --build . && ctest -VV
